#!/bin/bash
# postrm script for jolicloud-guestlogin

set -e

# update pam configuration files: common-auth, common-session, common-noninteractive
pam-auth-update --package

# remove guests group
if GUESTS_GROUP=`grep guests /etc/group` 2>/dev/null; then
    delgroup guests || true
fi

# remove configuration entry from slim configuration file
sed -ibackup -r \
    -e "/^#?guest_group.*\$/d" \
    -e "/^#?login_guest_cmd.*\$/d" \
    /etc/slim.conf

#DEBHELPER#

exit 0
