#!/bin/bash
# postrm script for jolicloud-guestlogin

set -e

# update pam configuration files: common-auth, common-session, common-noninteractive
pam-auth-update --package

# remove guests group
if GUESTS_GROUP=`grep guests /etc/group` 2>/dev/null; then
    delgroup guests
fi

# remove configuration entry from slim configuration file
tmp_file=$(mktemp)
chmod 0600 $tmp_file
grep -v "guest_" /etc/slim.conf > $tmp_file
cat $tmp_file > /etc/slim.conf
rm $tmp_file

#DEBHELPER#

exit 0
